name: Build, Test, and Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build.test.publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "pip install -r requirements.txt; pip install -e .;"
        docs-folder: "docs/"

    - name: pytest action
      run: |
        pytest
        
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.5.10
      if: github.event_name == 'push'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html
